### ISSUE TITLE
Attribute Error message

### ISSUE THREAD

**Issue by DedrichVonDorn** [oarepo/json-excel-converter#7]
Hi there, I am following a simple use scenario / test on Python3 and get this error:

Traceback (most recent call last):
  File "/Users/xxx/Documents/Projects/my_tools/utilty_json/convert_json_to_excel.py", line 43, in <module>
    conv.convert(data, writer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/json_excel_converter/converter.py", line 14, in convert
    self.convert_streaming(data, writer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/json_excel_converter/converter.py", line 24, in convert_streaming
    errors = self.conv.check(d)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/json_excel_converter/linearize.py", line 192, in check
    for k in value.keys():
AttributeError: 'str' object has no attribute 'keys'

Any help in this would be appreciated!

**Comment by DedrichVonDorn** [comment]
I think this is an error with the Json file itself... Sorry!
